version: '3.8'

services:
    app:
        build: .
        ports:
            - '3000:3000'
        depends_on:
            - mongo
        environment:
            MONGO_URI: mongodb://mongo:27017/mydatabase
            JWT_SECRET: your_jwt_secret_key
    mongo:
        image: mongo:4.4
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db
    mongo-express:
        image: mongo-express:0.54
        ports:
            - '8081:8081'
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin123

volumes:
    mongo-data:
