services:
    db:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
            ME_CONFIG_MONGODB_SERVER: db
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: shahriarDevMishal
    app:
        build: .
        restart: always
        ports:
            - '3000:3000'
        depends_on:
            - db
        environment:
            MONGO_URI: mongodb://root:example@db:27017/
            JWT_SECRET: your_jwt_secret_key

volumes:
    mongo-data:
